## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Francesca E Roberto Sposi"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Francesca E Roberto Sposi"
  logo = "images/banner.jpg"
  favicon = false

[Params.social]
  #github = "https://github.com/caressofsteel/"
  #twitter = "https://twitter.com/caressofsteel_"
  #email = "caressofsteel@protonmail.com"
  #instagram = "https://instagram.com"
  #linkedin = "https://linkedin.com"
  #telegram = "https://telegram.org"
